sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pmishra13/docker-reactapp -f Dockerfile.dev .

script:
  - docker run -e CI=true pmishra13/docker-reactapp npm run test -- --coverage
